// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BottomNavigation: typeof import('./src/components/BottomNavigation.vue')['default']
    CodeBlock: typeof import('./src/components/CodeBlock.vue')['default']
    Loader: typeof import('./src/components/loader.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    PuzzleSelector: typeof import('./src/components/PuzzleSelector.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
